---
- hosts: aws
  become: true
  tasks:
    - name: download audit files
      get_url:
        url: http://proceedwell.com/audit.rules.d.tar
        dest: /tmp/audit.rules.d.tar

    - name: unzip  and update rules
      shell: "cd /etc/audit/rules.d && tar xf /tmp/audit.rules.d.tar && /bin/rm /tmp/audit.rules.d.tar"

    - name: copy the hardening script and run
      template:
        src: template/part4_hardening.j2
        dest: /tmp/part4_hardening
        owner: root
        group: wheel
        mode: 0777

    - name: run the hardening
      shell: /tmp/part4_hardening && rm -f /tmp/part4_hardening
