---
- hosts: aws
  become: true
  tasks:
    - name: instlal yum
      yum:
        name: "tcp_wrappers"
    - name: add lines
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
      loop:
        - net.ipv4.ip_forward = 0
        - net.ipv4.conf.all.send_redirects = 0
        - net.ipv4.conf.default.send_redirects = 0
        - net.ipv4.conf.all.accept_source_route = 0
        - net.ipv4.conf.default.accept_source_route = 0
        - net.ipv4.conf.all.accept_redirects = 0
        - net.ipv4.conf.default.accept_redirects = 0
        - net.ipv4.conf.all.secure_redirects = 0
        - net.ipv4.conf.default.secure_redirects = 0
        - net.ipv4.conf.all.log_martians = 1
        - net.ipv4.conf.default.log_martians = 1
        - net.ipv4.icmp_echo_ignore_broadcasts = 1
        - net.ipv4.icmp_ignore_bogus_error_responses = 1
        - net.ipv4.conf.all.rp_filter = 1
        - net.ipv4.conf.default.rp_filter = 1
        - net.ipv4.tcp_syncookies = 1
    - name: part 3 commands
      shell: "{{ item }}"
      loop:
        - sysctl -w net.ipv4.ip_forward=0
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.send_redirects=0
        - sysctl -w net.ipv4.conf.default.send_redirects=0
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.accept_source_route=0
        - sysctl -w net.ipv4.conf.default.accept_source_route=0
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.accept_redirects=0
        - sysctl -w net.ipv4.conf.default.accept_redirects=0
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.secure_redirects=0
        - sysctl -w net.ipv4.conf.default.secure_redirects=0
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.log_martians=1
        - sysctl -w net.ipv4.conf.default.log_martians=1
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.icmp_echo_ignore_broadcasts=1
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.icmp_ignore_bogus_error_responses=1
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.conf.all.rp_filter=1
        - sysctl -w net.ipv4.conf.default.rp_filter=1
        - sysctl -w net.ipv4.route.flush=1
        - sysctl -w net.ipv4.tcp_syncookies=1
        - sysctl -w net.ipv4.route.flush=1
        # - iptables -P INPUT DROP
        # - iptables -P OUTPUT DROP
        # - iptables -P FORWARD DROP
        # - iptables -A INPUT -i lo -j ACCEPT
        # - iptables -A OUTPUT -o lo -j ACCEPT
        # - iptables -A INPUT -s 127.0.0.0/8 -j DROP
# echo "ALL: ALL" >> /etc/hosts.deny
